FROM docker.io/mysql:8.4.2

# mysqlのUIDを3901に。
RUN usermod -u 3901 mysql

ENV MYSQL_DATABASE=laravel \
  MYSQL_USER=tamakoma \
  MYSQL_PASSWORD=secret \
  MYSQL_ROOT_PASSWORD=secret \
  TZ=Asia/Tokyo
